---
- name: Verify
  hosts: instance
  gather_facts: false
  tasks:
    - name: Check dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      check_mode: true
      register: {{ cookiecutter.role_name }}_verify
      failed_when: {{ cookiecutter.role_name }}_verify.changed
...
